version: 0.4.0.{build}
branches:
  only:
    - appveyor
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
environment:
  matrix:
  - TARGET: nightly-x86_64-pc-windows-msvc
    ARCH: 64
  - TARGET: nightly-i686-pc-windows-msvc
    ARCH: 32
install:
  - cmd: echo Current directory is
  - cmd: cd
  - cmd: mkdir ..\deps
  - cmd: curl -so "..\deps\sciter%ARCH%.dll" "https://raw.githubusercontent.com/c-smile/sciter-sdk/master/bin/sciter%ARCH%.dll"
  - cmd: curl -so "..\deps\sciter%ARCH%.lib" "https://raw.githubusercontent.com/c-smile/sciter-sdk/master/lib/sciter%ARCH%.lib"
  - cmd: curl -so "..\deps\rust-install.exe" "https://static.rust-lang.org/dist/rust-%TARGET%.exe"
  - cmd: ..\deps\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust"
  - cmd: set PATH=%PATH%;C:\rust\bin;C:\projects\deps
build_script:
  - cmd: cd
  - cargo clean
  - cmd: echo Building library
  - cmd: mkdir target\release\deps
  - cmd: copy ..\deps\sciter%ARCH%.lib target\release\deps
  - cargo build --release
  - cmd: echo Building examples
  - cmd: mkdir examples\target\release\deps
  - cmd: copy ..\deps\sciter%ARCH%.lib examples\target\release\deps
  - cmd: cd examples
  - cargo build --release
  - cmd: cd ..
test_script:
  - cmd: cd
  - cargo test --release
